### ISSUE TITLE
Is that a way to limit input char length?

### ISSUE THREAD

**Issue by erhanfirat** [wojtekmaj/react-time-picker#64] opened 2019-12-26 12:19 UTC
I want to limit user key input to two. 
Now user can input more than 2 char to inputs even it does not affect to val. 

Thanks..

**Comment by wojtekmaj** [comment] 2019-12-29 15:47
Duplicate of #15

**Comment by wojtekmaj** [comment] 2019-12-29 15:47
With 6377396 this should no longer be an issue.

**Closed by wojtekmaj** 2019-12-29 15:47 UTC
Labels: duplicate, enhancement
