### ISSUE TITLE
Focus jumps from hours field to seconds field, missing the minutes field.

### ISSUE THREAD

**Issue by IndraManickam** [wojtekmaj/react-time-picker#282] opened 2023-03-28 01:57 UTC
When a user is typing values rapidly on the input field. the key-up event is fired rapidly.
The key-up function shifts the focus to the next field.  As a result, the key-up event that is later fired will consider the next field as the minute field.

Steps to reproduce.
1. Rapidly type 12 in the hour field.
2. Minute field should have a value more than or equal to 6.

Having a Scheduling logic before calling the focus will prevent the racing scenario between the user key-up event and the focus function.

**Comment by IndraManickam** [comment] 2023-03-30 03:07
@wojtekmaj  can you pls review the defect and the PR attached.

**Comment by IndraManickam** [comment] 2023-04-07 17:00
@wojtekmaj any updates?

**Comment by wojtekmaj** [comment] 2023-04-18 18:18
Duplicate of #131

**Closed by wojtekmaj** 2023-04-18 18:18 UTC
Labels: bug
