### ISSUE TITLE
Next.js not allowing global css import from node_modules

### ISSUE THREAD

**Issue by Merdi-kim** [wojtekmaj/react-time-picker#135] opened 2022-03-15 11:19 UTC
When working with next.js, an error is showing up saying that **Global CSS cannot be imported from within node_modules.** It would be better if there was a possibility of importing **Clock.css** manually so that the same error doesn't appear while working with next.js

**Comment by wojtekmaj** [comment] 2022-03-18 22:34
Duplicate of #134

**Closed by wojtekmaj** 2022-03-18 22:34 UTC
