### ISSUE TITLE
More than two digits can be added to the last input

### ISSUE THREAD

**Issue by jbojcic1** [wojtekmaj/react-time-picker#69] opened 2019-12-29 19:56 UTC
You can enter any number with any number of digits currently to the last input. Issue can be reproduced on the demo page:

![Screen Shot 2019-12-29 at 8 54 25 PM](https://user-images.githubusercontent.com/10374826/71561920-71fe6f00-2a7d-11ea-81b6-32a8431c7ee3.png)

If you don't use seconds, then same issue happens for minutes input. 

Expected behavior: It shouldn't be possible to enter invalid numbers or at least number of digits should be limited.

**Comment by jbojcic1** [comment] 2019-12-29 19:57
Example with minutes:

![Screen Shot 2019-12-29 at 8 57 29 PM](https://user-images.githubusercontent.com/10374826/71561960-e0dbc800-2a7d-11ea-92e4-e4b98af2a13a.png)

**Comment by wojtekmaj** [comment] 2019-12-29 20:52
Oh, the timing! 😄 

Fixed 5 hours ago in 63773968e23ab9886515ecd35a22a975c8eb3f5a.

**Comment by wojtekmaj** [comment] 2019-12-29 20:52
Duplicate of #45

**Closed by wojtekmaj** 2019-12-29 20:52 UTC

**Comment by jbojcic1** [comment] 2019-12-29 20:56
can we expect new release anytime soon?

**Comment by wojtekmaj** [comment] 2019-12-30 09:05
Yeah, busy at commercial projects at the moment but planning to release them this week or the next at the latest.
