### ISSUE TITLE
Allow selection of time at every 15 or 30 minutes interval

### ISSUE THREAD

**Issue by sabbiu** [wojtekmaj/react-time-picker#122] opened 2021-07-12 21:11 UTC
Is it possible to restrict the time selection at only 15 minutes interval?

So that user can select following time,

```
02: 15 pm
02: 30 pm
02: 45 pm
03: 00 pm
...and so on
```

User will not be able select following

```
02: 12 pm
02: 49 pm
... and so on
```

**Comment by wojtekmaj** [comment] 2021-07-14 21:29
Duplicate of #55

**Closed by wojtekmaj** 2021-07-14 21:29 UTC
