### ISSUE TITLE
Add TypeScript support 

### ISSUE THREAD

**Issue by nicolashedoire** [wojtekmaj/react-time-picker#90] opened 2020-06-19 18:06 UTC
npm install @types/react-time-picker

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types%2freact-time-picker - Not found
npm ERR! 404 
npm ERR! 404  '@types/react-time-picker@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by wojtekmaj** [comment] 2020-06-22 05:45
Duplicate of #33

**Closed** 2020-06-22 05:45 UTC
