### ISSUE TITLE
Minutes and seconds field input manually showing threedigits

### ISSUE THREAD

**Issue by shanmukhirukunaga** [wojtekmaj/react-time-picker#111] opened 2021-03-01 04:35 UTC
when I try to enter minutes field manually, from 01 to 09 it is showing numbers as 001,002,003,004,005,006,007,008,009.
I have attached a screenshot, plz check it
![109327490-67588900-787e-11eb-9358-328b679db29e](https://user-images.githubusercontent.com/76225434/109452402-a7ce2780-7a75-11eb-9fd2-f4c14ebdab16.png)

**Comment by wojtekmaj** [comment] 2021-03-01 04:38
Duplicate of #87

**Closed** 2021-03-01 04:38 UTC
Labels: bug, duplicate
