### ISSUE TITLE
Time control displays a triple 000 on the minutes and seconds inputs on occassions

### ISSUE THREAD

**Issue by NachoKai** [wojtekmaj/react-time-picker#94] opened 2020-07-28 12:32 UTC
This bug still exists in the latest version.
https://github.com/wojtekmaj/react-time-picker/issues/87

**Comment by wojtekmaj** [comment] 2020-08-03 16:22
Duplicate of #87

This ticket was not closed, so no need to create another one.

**Closed by wojtekmaj** 2020-08-03 16:22 UTC
